/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: 545536a10201d27e0a135b8356daf98d)
interface __BaseEnv_Env {
	VIDEOS: R2Bucket;
	MEDIA_ANALYTICS: AnalyticsEngineDataset;
	PLAYER_ORIGIN: "https://3x-storage.76.13.223.158.sslip.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PLAYER_ORIGIN">> {}
}
